### ISSUE TITLE
Ruby 2.4.0 depreciated warning

### ISSUE THREAD

**Issue by javiervg** [escline/linefit#5]
Thanks for the gem. Very nice implementation.

Everything works, but getting warning below. FYI,

/Users/.rvm/gems/ruby-2.4.0/gems/linefit-0.3.3/lib/linefit.rb:59: warning: constant ::FALSE is deprecated
/Users//.rvm/gems/ruby-2.4.0/gems/linefit-0.3.3/lib/linefit.rb:180: warning: constant ::TRUE is deprecated

**Comment by escline** [comment]
Thanks for the heads up. I fixed this by converting the boolean constants to valid true/false values. Gem 0.3.4 pushed to Rubygems.org.
